pool: 'Default'

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'feature-ms-pabloEscalona-mensaje'
    organization: 'escalonavil'
    scannerMode: 'MSBuild'
    projectKey: 'escalonavil_feature-ms-pabloEscalona-mensaje'
    projectName: 'feature-ms-pabloEscalona-mensaje'



  
  
