pool: 'Default'

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Pablo Escalona, se realiza la compilacion
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'feature-ms-pabloEscalona-mensaje'
    organization: 'escalonavil'
    scannerMode: 'MSBuild'
    projectKey: 'escalonavil_feature-ms-pabloEscalona-mensaje'
    projectName: 'feature-ms-pabloEscalona-mensaje'
  displayName: Se realiza la preparacion sonar cloud
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
  displayName: Se realiza el analisis sonar cloud
- task: Docker@2
  inputs:
    containerRegistry: 'docker pablo escalona'
    command: 'login'
  displayName: Se realiza el login docker
- task: Docker@2
  inputs:
    containerRegistry: 'docker pablo escalona'
    repository: 'escalonavil/PabloEscalonaLaboratorio'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
  displayName: Se realiza el build en docker  
- task: Docker@2
  inputs:
    containerRegistry: 'docker pablo escalona'
    repository: 'escalonavil/PabloEscalonaLaboratorio'
    command: 'push'
    tags: 'latest'
  displayName: Se realiza el push en docker
  





  
  
