pool: 'Default'

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

Settings
-task: SonarCloudPrepare@1
 inputs:
   SonarCloud: 'Sonarcloud'
   organization: 'escalonavil' 
   scannerMode:'MSBuild'
   projectKey: 'escalonavil_feature-ms-pabloEscalona-mensaje'
   projectName: 'escalonavil_feature-ms-pabloEscalona-mensaje'
   projectVersion: '2.6.0'

  
  
