name: feature-ms-pabloEscalona-mensaje

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Se configura java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
       
    - run: |
        chmod +x gradlew
        
    - name: Se genera el Build con Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
