on:
  issues:
    types: [opened, edited, milestoned]

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
   
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: Tablero
        issuetype: Task
        summary: Problema en repositorio ${{ github.repository }}
        description: Bug
        #fields: '{"customfield_10171": "test"}'
